# Generated by Django 5.1.1 on 2024-10-05 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_fullname', models.CharField(default='', max_length=200)),
                ('user_email', models.EmailField(default='', max_length=254)),
                ('user_age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('bike_id', models.AutoField(primary_key=True, serialize=False)),
                ('bike_model', models.CharField(default='', max_length=100)),
                ('bike_year', models.IntegerField()),
                ('bike_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.user')),
            ],
        ),
    ]
