# Generated by Django 5.1.1 on 2024-10-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.CharField(default='12345678', max_length=8),
        ),
    ]
