# Generated by Django 5.1.1 on 2024-10-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_user_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_plan',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
