# Generated by Django 5.1.1 on 2024-10-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_user_user_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_birthday',
            field=models.DateField(default='0001-01-01'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_cidade',
            field=models.CharField(default='city', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='user_data_validade',
            field=models.DateField(default='0001-01-01', verbose_name='mm/yyyy'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_dono_cartao',
            field=models.CharField(default='owner', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='user_estado',
            field=models.CharField(default='state', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='user_gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='m', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='user_nome_rua',
            field=models.CharField(default='lalal', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='user_number',
            field=models.CharField(default=12345678912, max_length=11),
        ),
        migrations.AddField(
            model_name='user',
            name='user_numero_cartao',
            field=models.CharField(default='0000000000000000', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='user_pais',
            field=models.CharField(default='country', max_length=100),
        ),
    ]
