# Generated by Django 5.1.1 on 2024-10-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_user_user_birthday_user_user_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_birthday',
            field=models.DateField(default='0000-00-00'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_data_validade',
            field=models.DateField(default='000-00-00', verbose_name='mm/yyyy'),
        ),
    ]
